export const types={
    API_ERROR:"API_ERROR",

    AUTH_SEND:"AUTH_SEND",
    AUTH_LOGOUT:"AUTH_LOGOUT",
    AUTH_ERROR:"AUTH_ERROR",
    AUTH_LOADING:"AUTH_LOADING",
    AUTH_RESPONSE:"AUTH_RESPONSE",
    
    CUSTOMER_GET:"CUSTOMER_GET", 
    CUSTOMER_PAGE_LOADING:"CUSTOMER_PAGE_LOADING",
    CUSTOMERS_GET_RESP:"CUSTOMERS_GET_RESP",
    CUSTOMER_GET_RESP:"CUSTOMER_GET_RESP",
    CUSTOMER_SET_INFO:"CUSTOMER_SET_INFO",
    CUSTOMER_SET_RESP:"CUSTOMER_SET_RESP",
    CUSTOMER_MODAL_OPEN:"CUSTOMER_MODAL_OPEN",
    CUSTOMER_MODAL_CLOSE:"CUSTOMER_MODAL_CLOSE",
    CUSTOMER_MODAL_LOADING:"CUSTOMER_MODAL_LOADING",
    CUSTOMER_DELETE:"CUSTOMER_DELETE",
    CUSTOMER_DELETE_RESP:"CUSTOMER_DELETE_RESP",
    CUSTOMER_API_ERROR:"CUSTOMER_API_ERROR",

    CUSTOMER_PAYMENTS_GET:"CUSTOMER_PAYMENTS_GET",
    CUSTOMER_PAYMENTS_LOADING:"CUSTOMER_PAYMENTS_LOADING",
    CUSTOMER_PAYMENTS_GET_RESP:"CUSTOMER_PAYMENTS_GET_RESP",
    CUSTOMER_PAYMENTS_API_ERROR:"CUSTOMER_PAYMENTS_API_ERROR",
};